In [1]:
import pandas as pd

In [2]:
graz_data = pd.read_csv('../data/data_train_reg.csv',index_col=0)

In [3]:
graz_data

,D_PM10K_mean,DonBosco_Temp_mean,DonBosco_RH_mean,N_PM10K_mean,Nord_Temp_mean,Nord_RH_mean,Nord_Pressure_mean,Nord_Precip_mean,Nord_Radiation_mean,Nord_Winddirection_mean,...,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,season_fall,season_spring,season_summer,season_winter,holiday,holiday_school
index,,,,,,,,,,,,,,,,,,,,,
2018-01-01,81.662500,2.866667,88.458333,30.354167,4.475000,80.791667,970.179167,0.057500,13.995833,237.500000,...,0,0,0,0,0,0,0,1,1,1
2018-01-02,23.812500,1.162500,95.000000,20.654167,1.637500,95.208333,971.066667,0.029167,43.045833,223.208333,...,0,0,1,0,0,0,0,1,0,1
2018-01-03,27.104167,0.791667,86.250000,19.200000,1.041667,85.833333,967.262500,0.004167,46.245833,217.958333,...,0,0,0,1,0,0,0,1,0,1
2018-01-04,32.279167,0.779167,88.000000,21.954167,0.937500,87.375000,965.850000,0.000000,36.545833,249.000000,...,0,1,0,0,0,0,0,1,0,1
2018-01-05,49.608333,3.291667,87.458333,27.400000,4.412500,84.083333,966.141667,0.000000,60.429167,172.791667,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-11,36.062500,12.062500,57.041667,17.370833,11.733333,56.541667,975.662500,0.000000,147.318997,209.708333,...,0,0,0,1,0,1,0,0,0,0
2020-03-12,50.116667,12.066667,64.500000,18.212500,12.162500,62.708333,975.816667,0.000000,147.318997,209.708333,...,0,1,0,0,0,1,0,0,0,0
2020-03-13,22.754167,7.950000,90.916667,12.970833,8.412500,84.916667,976.554167,0.035417,147.318997,207.250000,...,0,0,0,0,0,1,0,0,0,0
2020-03-14,19.679167,6.070833,70.458333,12.783333,5.775000,66.208333,981.608333,0.000000,147.318997,193.666667,...,0,0,0,0,0,1,0,0,0,0
2020-03-15,14.533333,4.279167,42.791667,14.033333,4.179167,49.750000,986.716667,0.000000,147.318997,191.000000,...,1,0,0,0,0,1,0,0,0,0

In [5]:
pollutants = ['D_PM10K_mean','N_PM10K_mean','O_PM10K_mean','S_PM10K_mean', 'W_PM10K_mean']

In [9]:
traffic_data = pd.read_csv('../data/promet.csv',index_col=0)

In [10]:
satelit_data = pd.read_csv('../data/satelit_data.csv',index_col=0)

In [11]:
temporal = ['year', 'dayofyear', 'month_Apr', 'month_Aug', 'month_Dec', 'month_Feb',
       'month_Jan', 'month_Jul', 'month_Jun', 'month_Mar', 'month_May',
       'month_Nov', 'month_Oct', 'month_Sep', 'weekday_Friday',
       'weekday_Monday', 'weekday_Saturday', 'weekday_Sunday',
       'weekday_Thursday', 'weekday_Tuesday', 'weekday_Wednesday',
       'season_fall', 'season_spring', 'season_summer', 'season_winter',
       'holiday', 'holiday_school']

In [12]:
sites = ['DonBosco','Nord','Ost','Sud','West']

satelit = ['Temperature_Air_2m_Mean_24h', 'Cloud_Cover_Mean',
       'Wind_Speed_10m_Mean', 'Dew_Point_Temperature_2m_Mean',
       'Vapour_Pressure_Mean']

In [24]:
def split_data(var_name, site_name, PM, rest_data):
    temp_y = PM[var_name]
    temp_y.name = var_name
    temp_temporal = rest_data[temporal]
    temp_x = rest_data.filter(like=site_name, axis=1)
    temp_x = pd.concat([temp_x, temp_temporal,temp_y], axis=1)
    return temp_x

In [27]:
def prep_data_satelite(temp_x, site, data):
    weather_data = temp_x.filter(like=site, axis=1)
    temp_x = temp_x.drop(columns=weather_data.columns, axis=1)
    temp_x = pd.concat([temp_x, data], axis=1)
    return temp_x

In [37]:
def traffic_for_station(site_temp, data_temp):
    traffic_temp = data_temp.filter(like=site_temp, axis=1)
    return traffic_temp

In [48]:
for varname,site in zip(pollutants,sites):
    df = split_data(varname,site,PM,rest_data)
    #df.to_csv(f'../data_for_testing/local_{varname}_{site}.csv')
    df_1 = prep_data_satelite(df,site,satelit_data)
    #df_1.to_csv(f'../data_for_testing/satelite_{varname}_{site}.csv')
    df_2 = pd.concat([df,satelit_data],axis=1)
    #df_2.to_csv(f'../data_for_testing/all_meteo_{varname}_{site}.csv')
    traffic_station = traffic_for_station(site,traffic_data)
    df_3 = pd.concat([df,traffic_station],axis=1)
    #df_3.to_csv(f'../data_for_testing/local_traffic_{varname}_{site}.csv')
    df_4 = pd.concat([df_1,traffic_station],axis=1)
    #df_4.to_csv(f'../data_for_testing/satelit_traffic_{varname}_{site}.csv')
    df_5 = pd.concat([df_2,traffic_station],axis=1)
    #df_5.to_csv(f'../data_for_testing/all_traffic_{varname}_{site}.csv')