In [1]:
import pandas as pd

In [2]:
graz_data = pd.read_csv('../data/data_train_reg.csv',index_col=0)

In [3]:
graz_data

,D_PM10K_mean,DonBosco_Temp_mean,DonBosco_RH_mean,N_PM10K_mean,Nord_Temp_mean,Nord_RH_mean,Nord_Pressure_mean,Nord_Precip_mean,Nord_Radiation_mean,Nord_Winddirection_mean,...,weekday_Sunday,weekday_Thursday,weekday_Tuesday,weekday_Wednesday,season_fall,season_spring,season_summer,season_winter,holiday,holiday_school
index,,,,,,,,,,,,,,,,,,,,,
2018-01-01,81.662500,2.866667,88.458333,30.354167,4.475000,80.791667,970.179167,0.057500,13.995833,237.500000,...,0,0,0,0,0,0,0,1,1,1
2018-01-02,23.812500,1.162500,95.000000,20.654167,1.637500,95.208333,971.066667,0.029167,43.045833,223.208333,...,0,0,1,0,0,0,0,1,0,1
2018-01-03,27.104167,0.791667,86.250000,19.200000,1.041667,85.833333,967.262500,0.004167,46.245833,217.958333,...,0,0,0,1,0,0,0,1,0,1
2018-01-04,32.279167,0.779167,88.000000,21.954167,0.937500,87.375000,965.850000,0.000000,36.545833,249.000000,...,0,1,0,0,0,0,0,1,0,1
2018-01-05,49.608333,3.291667,87.458333,27.400000,4.412500,84.083333,966.141667,0.000000,60.429167,172.791667,...,0,0,0,0,0,0,0,1,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2020-03-11,36.062500,12.062500,57.041667,17.370833,11.733333,56.541667,975.662500,0.000000,147.318997,209.708333,...,0,0,0,1,0,1,0,0,0,0
2020-03-12,50.116667,12.066667,64.500000,18.212500,12.162500,62.708333,975.816667,0.000000,147.318997,209.708333,...,0,1,0,0,0,1,0,0,0,0
2020-03-13,22.754167,7.950000,90.916667,12.970833,8.412500,84.916667,976.554167,0.035417,147.318997,207.250000,...,0,0,0,0,0,1,0,0,0,0
2020-03-14,19.679167,6.070833,70.458333,12.783333,5.775000,66.208333,981.608333,0.000000,147.318997,193.666667,...,0,0,0,0,0,1,0,0,0,0
2020-03-15,14.533333,4.279167,42.791667,14.033333,4.179167,49.750000,986.716667,0.000000,147.318997,191.000000,...,1,0,0,0,0,1,0,0,0,0

In [5]:
pollutants = ['D_PM10K_mean','N_PM10K_mean','O_PM10K_mean','S_PM10K_mean', 'W_PM10K_mean']

In [9]:
traffic_data = pd.read_csv('../data/promet.csv',index_col=0)

In [10]:
satelit_data = pd.read_csv('../data/satelit_data.csv',index_col=0)

In [ ]:
def prep_data(var_name, site_name, PM, rest_data):
    temp_y = PM[var_name]
    temp_y.name = var_name
    temp_temporal = rest_data[temporal]
    temp_x = rest_data.filter(like=site_name, axis=1)
    temp_x = pd.concat([temp_x, temp_temporal], axis=1)
    return temp_x, temp_y

In [ ]:
def split_data

In [ ]:
for varname,site in zip(pollutants,sites):