In [53]:

import seaborn as sns
import pandas as pd
import numpy as np
from windrose import WindroseAxes
from matplotlib import pyplot as plt
import matplotlib.cm as cm
sns.set_style('whitegrid')

In [22]:
df=pd.read_csv('../data/full_data.csv', index_col=0)
df.index = pd.to_datetime(df.index)

In [23]:
data = df.fillna(method='bfill')

In [24]:
data.reset_index(inplace=True)

In [25]:
data['index'] = pd.to_datetime(data['index'])
data['year'] = data['index'].dt.year

In [26]:
a = data.groupby(pd.Grouper(key='index', freq='D')).mean()

In [27]:
a = a['2018-01-01':'2020-03-15']

In [79]:
ws = a.filter(like='Windspeed',axis=1)
wd = a.filter(like='Winddirection', axis=1)

In [83]:
windrose_data = pd.concat([ws,wd],axis=1)

,Nord_Windspeed,Ost_Windspeed,Sud_Windspeed,West_Windspeed,Nord_Winddirection,Ost_Winddirection,Sud_Winddirection,West_Winddirection
index,,,,,,,,
2018-01-01,0.525000,0.354167,0.325000,0.483333,237.500000,156.791667,189.333333,197.666667
2018-01-02,0.333333,0.275000,0.150000,0.245833,223.208333,183.750000,168.791667,228.291667
2018-01-03,0.366667,0.279167,0.254167,0.304167,217.958333,191.458333,211.666667,183.250000
2018-01-04,0.279167,0.237500,0.166667,0.254167,249.000000,167.583333,219.333333,212.333333
2018-01-05,0.516667,0.258333,0.237500,0.212500,172.791667,185.333333,212.500000,171.083333
...,...,...,...,...,...,...,...,...
2020-03-11,0.612500,0.541667,0.737500,0.529167,209.708333,246.458333,207.500000,226.458333
2020-03-12,0.908333,0.525000,0.595833,0.612500,209.708333,259.250000,195.916667,169.833333
2020-03-13,0.704167,0.408333,0.700000,0.479167,207.250000,226.833333,192.541667,211.291667
2020-03-14,0.708333,0.645833,0.804167,0.487500,193.666667,176.166667,189.416667,179.958333
2020-03-15,0.666667,0.500000,0.733333,0.637500,191.000000,178.750000,137.708333,170.500000

In [84]:
windrose_data.to_csv('windrose_data.csv')